### ISSUE TITLE
Guest Sanity: Stress tests failing

### ISSUE THREAD

**Issue by tengrui** [open-power-host-os/tests#11]
**Guest Sanity: Stress tests failing**

**Reason for Failure:**
Gcc is not installed inside guest, ideally it should be available during guest install but default fedora guest iso does not have it.

**Testcases affected:**
174-guest_sanity.stress.disk.qemu.qcow2.spapr_vscsi.smp2.spapr-vlan.Fedora.23.ppc64le.io-github-autotest-qemu.autotest.dbench

**Resolution action:**
This should be fixed in the future guest versions where we can install gcc by default.

**Workaround:**
Yum install gcc manually and try the test.

**Comment by rquander** [comment]
We are working on full dependency list documentation and automatic checks via Issues #14 & #15 .  Once gcc is included in these issue resolutions, this issue will be closed.

**Comment by sathnaga** [comment]
Fixed by install dependancies(guest_install):
TESTS : 3
(1/3) guest_install.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.http_ks.default_install.aio_native: PASS (474.36 s)
(2/3) guest_dep_install.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-qemu.guest_test.isa_serial_operations: PASS (34.86 s)
(3/3) guest_remove.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-libvirt.remove_guest.without_disk: PASS (9.69 s)
RESULTS : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 518.90 s
----
guest_sanity.stress.import.qemu.qcow2.spapr_vscsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-qemu.unattended_install.import.import.default_install.aio_native: PASS (55.26 s)
 (2/3) guest_sanity.stress.disk.qemu.qcow2.spapr_vscsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-qemu.autotest.dbench: PASS (169.52 s)
 (3/3) guest_sanity.stress.delete_guest.qemu.qcow2.spapr_vscsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-libvirt.remove_guest.without_disk: PASS (10.06 s)

closing bug
