### ISSUE TITLE
Sprint 1: test bz: CPU & Memory hotplug: DRC state info transmission for migration

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/tests#63]
This is test bz to track the testcases development for below new feature targeted for sprint 1:
123907 CPU & Memory hotplug: DRC state info transmission for migration

@sathnaga will be test owner.

@sathnaga please update with the testcases meant for testing this new feature.

<cde:info> Mirrored with LTC bug #158309 </cde:info>

**Comment by bssrikanth** [comment]
I believe testing this feature is similar to #60. So same testcase should hold good.

1. Create guest with shared storage in NFS
2. Enabled ports 49152:49216 in iptables, virt_use_nfs -> on
3. Mount the image location in destination and started migration.
4. Perform CPU Hotplug and Hotunplug, migrate to other host and perform CPU Hotplug and Hotunplug
CPU hot unplug should be successful

**Comment by bssrikanth** [comment]
since its similar to #60 Bala would be testing this feature.

**Comment by cdeadmin** [comment]
------- Comment From danielhb@br.ibm.com 2017-09-06 07:45:02 EDT-------
In step 4:

&quot;4. Perform CPU Hotplug and Hotunplug, migrate to other host and perform CPU Hotplug and Hotunplug&quot;

I am unsure if this is what it meant but If you hotplug and unplug a CPU before migration, migrate, then hotplug and unplug a CPU in destination you will not be testing the bug reported in 123907.

The sequence of events to reproduce that issue is:

- start VM in source host
- hotplug a CPU
- migrate to destination
- hotunplug the CPU

Or, putting in a sentence:

&quot;4. Perform CPU Hotplug, migrate to other host and perform CPU Hotunplug&quot;

Thanks,

Daniel

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-09-08 01:10:55 EDT-------
(In reply to comment #5)
&gt; In step 4:
&gt; 
&gt; &quot;4. Perform CPU Hotplug and Hotunplug, migrate to other host and perform CPU
&gt; Hotplug and Hotunplug&quot;
&gt; 
&gt; I am unsure if this is what it meant but If you hotplug and unplug a CPU
&gt; before migration, migrate, then hotplug and unplug a CPU in destination you
&gt; will not be testing the bug reported in 123907.
&gt; 
&gt; The sequence of events to reproduce that issue is:
&gt; 
&gt; - start VM in source host
&gt; - hotplug a CPU
&gt; - migrate to destination
&gt; - hotunplug the CPU
&gt; 
&gt; Or, putting in a sentence:
&gt; 
&gt; &quot;4. Perform CPU Hotplug, migrate to other host and perform CPU Hotunplug&quot;
&gt; 
&gt; 
&gt; Thanks,
&gt; 
&gt; 
&gt; Daniel

@Daniel thanks for the review. Ack'ed on behalf of @Bala.

**Comment by bssrikanth** [comment]
This is tested.

1. Hotplug 64 cpus to guest in source.
# virsh setvcpus avocado-vt-vm1-migration 64 --live
2. migrate vm to destination machine.
# virsh migrate avocado-vt-vm1-migration qemu+ssh://9.40.193.221/system --live --verbose
root@9.40.193.221's password: 
Migration: [100 %]
3. Hotunplug 56 cpus to guest in destination
# virsh setvcpus avocado-vt-vm1-migration 8 --live
# echo $?
0
Checked the respective change in cpu nos from inside guest. It's successful.
