### ISSUE TITLE
Update ReadMe Guest OS Support List

### ISSUE THREAD

**Issue by rquander** [open-power-host-os/tests#79]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=160453 </cde:info>

Recent updates submitted via the following commit enable support for running the Guest tests against additional Guest VM OS's, namely Ubuntu and SLES: https://github.com/open-power-host-os/tests/commit/ef90bb291836839285953f1497cc4dd29e8c6ab0

The OS Support section of the ReadMe needs to be updated so that users know what specific OS versions have been validated with this suite.

**Comment by rquander** [comment]
@sathnaga Please advise on which specific Guest VM OS versions we should add to the ReadMe.  Thanks!

**Comment by cdeadmin** [comment]
------- Comment From rquander@us.ibm.com 2018-04-13 16:32:55 EDT-------
It has been a while and I still do not have any new info to make sure the README is accurate for users.  

Please reply with the list of specific OS types and versions that have been successfully tested with Host OS so that I can ensure the ReadMe is updated with this info (or you can submit a PR with the updated info and I can review/approve it).

Thanks!

- Reina

**Comment by cdeadmin** [comment]
------- Comment From rquander@us.ibm.com 2018-08-23 15:08:34 EDT-------
Assigning to Murilo.
